{"name": "test_no_problem", "status": "passed", "description": "Function responsible for the unsucessful register in the application with an existant username (similar to 1.2)\n    \n    Arguments:\n        None\n\n    Returns:\n        1 if the test is successful (App's response is the intended), 0 otherwise\n    \n    Raises:\n        Exception if the login page could not be loaded\n    ", "start": 1699311159374, "stop": 1699311165202, "uuid": "4b753d76-93e9-49de-8adb-4ea5b9aa3789", "historyId": "3b4f19322b425ff8955200f774617bfa", "testCaseId": "3b4f19322b425ff8955200f774617bfa", "fullName": "REQ1.test_1_3_Register_No_Problems#test_no_problem", "labels": [{"name": "story", "value": "Registo com username existente na aplicação"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "REQ1 - Pagina de Login e Registo"}, {"name": "parentSuite", "value": "REQ1"}, {"name": "suite", "value": "test_1_3_Register_No_Problems"}, {"name": "host", "value": "linux-VirtualBox"}, {"name": "thread", "value": "18164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "REQ1.test_1_3_Register_No_Problems"}]}