{"name": "test_login_good_name_bad_pass", "status": "passed", "description": "Function responsible for the unsuccessful login with the valid username and invalid password\n    \n    Arguments:\n        None\n\n    Returns:\n        1 if the test is successful (App's response is the intended), 0 otherwise\n    \n    Raises:\n        If the login page could not be loaded\n    ", "start": 1699311174947, "stop": 1699311180156, "uuid": "1ce0f435-8a88-4d6e-9b9e-85c2672c9d6a", "historyId": "b2487d77c3c4a491619f9ef1bd40d728", "testCaseId": "b2487d77c3c4a491619f9ef1bd40d728", "fullName": "REQ1.test_1_5_Login_Good_Name_Bad_Pass#test_login_good_name_bad_pass", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "REQ1 - Pagina de Login e Registo"}, {"name": "story", "value": "Teste de Login com username válido e password inválida"}, {"name": "parentSuite", "value": "REQ1"}, {"name": "suite", "value": "test_1_5_Login_Good_Name_Bad_Pass"}, {"name": "host", "value": "linux-VirtualBox"}, {"name": "thread", "value": "18164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "REQ1.test_1_5_Login_Good_Name_Bad_Pass"}]}